(() => {
  const canvas = document.getElementById('arena');
  const ctx = canvas.getContext('2d');
  const ui = { health: document.getElementById('health-text'), healthBar: document.getElementById('health-bar'), wave: document.getElementById('wave-text'), score: document.getElementById('score-text'), essence: document.getElementById('essence-text'), start: document.getElementById('start-screen'), over: document.getElementById('game-over'), final: document.getElementById('final-stats'), banner: document.getElementById('wave-banner') };
  const keys = new Set();
  let state, lastTime = 0, animationId, touchAim = false, mouse = { x: 0, y: 0, down: false }, touchMove = { active: false, x: 0, y: 0 };
  const types = [{ name: 'crawler', color: '#e85d75', size: 15, speed: 55, hp: 1, damage: 8, points: 10 }, { name: 'wisp', color: '#a983ff', size: 11, speed: 85, hp: 1, damage: 5, points: 15 }, { name: 'brute', color: '#ff8c42', size: 24, speed: 32, hp: 3, damage: 16, points: 35 }];
  const rand = (min, max) => Math.random() * (max - min) + min;
  const distance = (a, b) => Math.hypot(a.x - b.x, a.y - b.y);
  function resize() { const box = canvas.getBoundingClientRect(); const dpr = Math.min(devicePixelRatio || 1, 2); canvas.width = box.width * dpr; canvas.height = box.height * dpr; ctx.setTransform(dpr, 0, 0, dpr, 0, 0); if (state) { state.w = box.width; state.h = box.height; state.player.x = Math.min(state.player.x, state.w - 30); state.player.y = Math.min(state.player.y, state.h - 30); } }
  function reset() { const rect = canvas.getBoundingClientRect(); state = { w: rect.width, h: rect.height, active: true, health: 100, wave: 1, score: 0, essence: 0, spawnLeft: 5, spawnTimer: 0, waveCooldown: 0, player: { x: rect.width / 2, y: rect.height / 2, r: 13, angle: 0, fireTimer: 0, invulnerable: 0 }, enemies: [], bullets: [], particles: [], drops: [], shake: 0 }; updateUi(); announceWave(); }
  function updateUi() { ui.health.textContent = `${Math.max(0, Math.ceil(state.health))} / 100`; ui.healthBar.style.width = `${Math.max(0, state.health)}%`; ui.healthBar.style.background = state.health < 30 ? '#ff6b5e' : '#d4ff3f'; ui.wave.textContent = state.wave; ui.score.textContent = String(state.score).padStart(6, '0'); ui.essence.textContent = state.essence; }
  function announceWave() { ui.banner.textContent = `WAVE ${state.wave}`; ui.banner.classList.remove('show'); void ui.banner.offsetWidth; ui.banner.classList.add('show'); }
  function spawnEnemy() { const type = types[Math.random() < .16 + state.wave * .015 ? 2 : Math.random() < .45 ? 1 : 0]; const side = Math.floor(rand(0, 4)); const edge = side % 2 ? rand(20, state.h - 20) : rand(20, state.w - 20); const x = side === 0 ? -30 : side === 1 ? state.w + 30 : edge; const y = side === 2 ? -30 : side === 3 ? state.h + 30 : edge; state.enemies.push({ ...type, x, y, maxHp: type.hp, hit: 0, phase: rand(0, 7) }); }
  function fire() { if (state.player.fireTimer > 0) return; const p = state.player; state.bullets.push({ x: p.x + Math.cos(p.angle) * 20, y: p.y + Math.sin(p.angle) * 20, vx: Math.cos(p.angle) * 650, vy: Math.sin(p.angle) * 650, life: .75 }); p.fireTimer = .13; for (let i = 0; i < 3; i++) state.particles.push({ x: p.x + Math.cos(p.angle) * 22, y: p.y + Math.sin(p.angle) * 22, vx: rand(-30, 30) + Math.cos(p.angle) * rand(40, 90), vy: rand(-30, 30) + Math.sin(p.angle) * rand(40, 90), life: .22, color: '#d4ff3f', size: rand(1, 3) }); }
  function damagePlayer(amount) { if (state.player.invulnerable > 0) return; state.health -= amount; state.player.invulnerable = .6; state.shake = 8; for (let i = 0; i < 8; i++) state.particles.push({ x: state.player.x, y: state.player.y, vx: rand(-100, 100), vy: rand(-100, 100), life: .4, color: '#ff6b5e', size: rand(2, 5) }); if (state.health <= 0) endGame(); }
  function killEnemy(enemy) { state.score += enemy.points; state.essence++; state.drops.push({ x: enemy.x, y: enemy.y, life: 8, spin: rand(0, 6) }); for (let i = 0; i < 10; i++) state.particles.push({ x: enemy.x, y: enemy.y, vx: rand(-120, 120), vy: rand(-120, 120), life: .6, color: enemy.color, size: rand(2, 5) }); }
  function endGame() { state.active = false; ui.final.textContent = `Wave ${state.wave} · ${String(state.score).padStart(6, '0')} points · ${state.essence} essence harvested`; ui.over.classList.remove('hidden'); }
  function update(dt) { const p = state.player; const target = touchAim && state.enemies.length ? state.enemies.reduce((nearest, enemy) => distance(enemy, p) < distance(nearest, p) ? enemy : nearest, state.enemies[0]) : null; p.angle = target ? Math.atan2(target.y - p.y, target.x - p.x) : Math.atan2(mouse.y - p.y, mouse.x - p.x); p.fireTimer -= dt; p.invulnerable -= dt; state.shake *= .9; if (mouse.down) fire(); let dx = (keys.has('d') || keys.has('arrowright') ? 1 : 0) - (keys.has('a') || keys.has('arrowleft') ? 1 : 0); let dy = (keys.has('s') || keys.has('arrowdown') ? 1 : 0) - (keys.has('w') || keys.has('arrowup') ? 1 : 0); if (touchMove.active) { dx += touchMove.x; dy += touchMove.y; } const magnitude = Math.hypot(dx, dy) || 1; p.x = Math.max(24, Math.min(state.w - 24, p.x + dx / magnitude * 230 * dt)); p.y = Math.max(24, Math.min(state.h - 24, p.y + dy / magnitude * 230 * dt));
    if (state.spawnLeft > 0) { state.spawnTimer -= dt; if (state.spawnTimer <= 0) { spawnEnemy(); state.spawnLeft--; state.spawnTimer = Math.max(.16, .7 - state.wave * .025); } } else if (!state.enemies.length) { state.waveCooldown += dt; if (state.waveCooldown > 1.2) { state.wave++; state.spawnLeft = 4 + state.wave * 2; state.waveCooldown = 0; announceWave(); } }
    state.bullets.forEach(b => { b.x += b.vx * dt; b.y += b.vy * dt; b.life -= dt; }); state.bullets = state.bullets.filter(b => b.life > 0 && b.x > -20 && b.x < state.w + 20 && b.y > -20 && b.y < state.h + 20);
    state.enemies.forEach(e => { const angle = Math.atan2(p.y - e.y, p.x - e.x); e.x += Math.cos(angle) * e.speed * (1 + state.wave * .012) * dt; e.y += Math.sin(angle) * e.speed * (1 + state.wave * .012) * dt; e.hit -= dt; if (distance(e, p) < e.size + p.r) { damagePlayer(e.damage * dt); } });
    state.bullets.forEach(b => state.enemies.forEach(e => { if (distance(b, e) < e.size + 4 && b.life > 0) { b.life = 0; e.hp--; e.hit = .1; if (e.hp <= 0) killEnemy(e); } })); state.enemies = state.enemies.filter(e => e.hp > 0);
    state.drops.forEach(d => { d.life -= dt; d.spin += dt * 4; if (distance(d, p) < 26) { d.life = 0; state.health = Math.min(100, state.health + 10); } }); state.drops = state.drops.filter(d => d.life > 0); state.particles.forEach(x => { x.x += x.vx * dt; x.y += x.vy * dt; x.life -= dt; }); state.particles = state.particles.filter(x => x.life > 0); updateUi(); }
  function draw() { const w = state.w, h = state.h; ctx.clearRect(0, 0, w, h); ctx.save(); ctx.translate(rand(-state.shake, state.shake), rand(-state.shake, state.shake)); ctx.fillStyle = '#0c1719'; ctx.fillRect(0, 0, w, h); ctx.strokeStyle = 'rgba(153, 208, 183, .07)'; ctx.lineWidth = 1; for (let x = 0; x < w; x += 44) { ctx.beginPath(); ctx.moveTo(x, 0); ctx.lineTo(x, h); ctx.stroke(); } for (let y = 0; y < h; y += 44) { ctx.beginPath(); ctx.moveTo(0, y); ctx.lineTo(w, y); ctx.stroke(); } state.drops.forEach(d => { ctx.save(); ctx.translate(d.x, d.y); ctx.rotate(d.spin); ctx.fillStyle = '#d4ff3f'; ctx.shadowColor = '#d4ff3f'; ctx.shadowBlur = 14; ctx.fillRect(-6, -6, 12, 12); ctx.restore(); }); state.particles.forEach(x => { ctx.globalAlpha = Math.max(0, x.life * 2); ctx.fillStyle = x.color; ctx.beginPath(); ctx.arc(x.x, x.y, x.size, 0, Math.PI * 2); ctx.fill(); }); ctx.globalAlpha = 1; state.bullets.forEach(b => { ctx.strokeStyle = '#f5ffb0'; ctx.lineWidth = 3; ctx.beginPath(); ctx.moveTo(b.x, b.y); ctx.lineTo(b.x - b.vx * .025, b.y - b.vy * .025); ctx.stroke(); }); state.enemies.forEach(e => { ctx.save(); ctx.translate(e.x, e.y); ctx.rotate(Math.atan2(state.player.y - e.y, state.player.x - e.x)); ctx.fillStyle = e.hit > 0 ? '#fff' : e.color; ctx.shadowColor = e.color; ctx.shadowBlur = e.name === 'brute' ? 18 : 10; ctx.beginPath(); ctx.arc(0, 0, e.size, 0, Math.PI * 2); ctx.fill(); ctx.fillStyle = '#101719'; ctx.fillRect(e.size * .1, -e.size * .42, 4, 4); ctx.fillRect(e.size * .1, e.size * .18, 4, 4); if (e.maxHp > 1) { ctx.shadowBlur = 0; ctx.fillStyle = '#172124'; ctx.fillRect(-e.size, -e.size - 9, e.size * 2, 3); ctx.fillStyle = '#ff8c42'; ctx.fillRect(-e.size, -e.size - 9, e.size * 2 * e.hp / e.maxHp, 3); } ctx.restore(); }); const p = state.player; ctx.save(); ctx.translate(p.x, p.y); ctx.rotate(p.angle); ctx.globalAlpha = p.invulnerable > 0 && Math.floor(p.invulnerable * 14) % 2 ? .4 : 1; ctx.fillStyle = '#d4ff3f'; ctx.shadowColor = '#d4ff3f'; ctx.shadowBlur = 18; ctx.beginPath(); ctx.arc(0, 0, p.r, 0, Math.PI * 2); ctx.fill(); ctx.fillStyle = '#112022'; ctx.fillRect(5, -4, 20, 8); ctx.restore(); ctx.restore(); }
  function loop(time) { const dt = Math.min(.033, (time - lastTime) / 1000 || 0); lastTime = time; if (state?.active) update(dt); if (state) draw(); animationId = requestAnimationFrame(loop); }
  function start() { ui.start.classList.add('hidden'); ui.over.classList.add('hidden'); reset(); cancelAnimationFrame(animationId); animationId = requestAnimationFrame(loop); }
  function pointerPosition(event) { const rect = canvas.getBoundingClientRect(); mouse.x = event.clientX - rect.left; mouse.y = event.clientY - rect.top; }
  function setJoystick(event) { const stick = document.getElementById('joystick'); const knob = document.getElementById('joystick-knob'); const rect = stick.getBoundingClientRect(); const max = 35; const x = event.clientX - (rect.left + rect.width / 2); const y = event.clientY - (rect.top + rect.height / 2); const length = Math.min(max, Math.hypot(x, y)); const angle = Math.atan2(y, x); touchMove.x = Math.cos(angle) * length / max; touchMove.y = Math.sin(angle) * length / max; knob.style.transform = `translate(${touchMove.x * max}px, ${touchMove.y * max}px)`; touchMove.active = true; }
  function releaseJoystick() { touchMove.active = false; touchMove.x = 0; touchMove.y = 0; document.getElementById('joystick-knob').style.transform = ''; }
  async function toggleFullscreen() { const root = document.documentElement; if (!document.fullscreenElement && !document.webkitFullscreenElement) { const request = root.requestFullscreen || root.webkitRequestFullscreen; if (request) await request.call(root); } else { const exit = document.exitFullscreen || document.webkitExitFullscreen; if (exit) await exit.call(document); } }
  function updateFullscreenLabel() { const fullscreen = document.fullscreenElement || document.webkitFullscreenElement; document.querySelector('#fullscreen-button span').textContent = fullscreen ? 'EXIT FULLSCREEN' : 'FULLSCREEN'; }
  const joystick = document.getElementById('joystick'); joystick.addEventListener('pointerdown', event => { if (event.isPrimary) joystick.setPointerCapture(event.pointerId); setJoystick(event); }); joystick.addEventListener('pointermove', event => { if (touchMove.active) setJoystick(event); }); joystick.addEventListener('pointerup', releaseJoystick); joystick.addEventListener('pointercancel', releaseJoystick);
  const touchFire = document.getElementById('touch-fire'); touchFire.addEventListener('pointerdown', event => { event.preventDefault(); if (event.isPrimary) touchFire.setPointerCapture(event.pointerId); touchAim = true; mouse.down = true; }); ['pointerup', 'pointercancel', 'pointerleave'].forEach(name => touchFire.addEventListener(name, () => { touchAim = false; mouse.down = false; }));
  document.getElementById('fullscreen-button').addEventListener('click', toggleFullscreen); document.addEventListener('fullscreenchange', updateFullscreenLabel); document.addEventListener('webkitfullscreenchange', updateFullscreenLabel); document.getElementById('start-button').addEventListener('click', start); document.getElementById('restart-button').addEventListener('click', start); window.addEventListener('resize', resize); window.addEventListener('keydown', event => { keys.add(event.key.toLowerCase()); if (['w', 'a', 's', 'd', 'arrowup', 'arrowdown', 'arrowleft', 'arrowright', ' '].includes(event.key.toLowerCase())) event.preventDefault(); }); window.addEventListener('keyup', event => keys.delete(event.key.toLowerCase())); canvas.addEventListener('pointermove', pointerPosition); canvas.addEventListener('pointerdown', event => { pointerPosition(event); mouse.down = true; canvas.setPointerCapture(event.pointerId); }); canvas.addEventListener('pointerup', () => { mouse.down = false; }); resize();
})();