#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Generates 166 new Chinese quiz questions for Singapore primary school:
  - 87 x 汉语拼音 (CHN105–CHN191)
  - 79 x 词汇     (CHN192–CHN270)
Prints a JSON array to stdout.
"""
import json

questions = []

# ──────────────────────────────────────────────
# 汉语拼音  P1-P2  CHN105–CHN130  (26 questions)
# ──────────────────────────────────────────────
questions += [
  {"id":"CHN105","category":"汉语拼音","difficulty":"P1-P2",
   "template":"{CHARACTER_0}每天「上学」，下列哪个是「上学」的正确拼音？",
   "placeholder_roles":["protagonist"],
   "options":["shàng xué","shǎng xué","shàng xuě","shāng xué"],
   "answer":0,"correct_answer":"shàng xué"},
  {"id":"CHN106","category":"汉语拼音","difficulty":"P1-P2",
   "template":"放学了，{CHARACTER_0}高兴地「下课」，下列哪个是「下课」的正确拼音？",
   "placeholder_roles":["protagonist"],
   "options":["xià kè","xiā kè","xià kě","xiǎ kè"],
   "answer":0,"correct_answer":"xià kè"},
  {"id":"CHN107","category":"汉语拼音","difficulty":"P1-P2",
   "template":"{CHARACTER_0}喜欢吃「水果」，下列哪个是「水果」的正确拼音？",
   "placeholder_roles":["protagonist"],
   "options":["shuǐ guǒ","shuì guǒ","shuǐ guō","shuí guǒ"],
   "answer":0,"correct_answer":"shuǐ guǒ"},
  {"id":"CHN108","category":"汉语拼音","difficulty":"P1-P2",
   "template":"{CHARACTER_0}最喜欢吃「苹果」，下列哪个是「苹果」的正确拼音？",
   "placeholder_roles":["protagonist"],
   "options":["píng guǒ","pīng guǒ","píng guō","pǐng guǒ"],
   "answer":0,"correct_answer":"píng guǒ"},
  {"id":"CHN109","category":"汉语拼音","difficulty":"P1-P2",
   "template":"妈妈买了「香蕉」，下列哪个是「香蕉」的正确拼音？",
   "placeholder_roles":[],
   "options":["xiāng jiāo","xiáng jiāo","xiāng jiào","xiǎng jiāo"],
   "answer":0,"correct_answer":"xiāng jiāo"},
  {"id":"CHN110","category":"汉语拼音","difficulty":"P1-P2",
   "template":"{CHARACTER_0}的衬衫是「白色」的，下列哪个是「白色」的正确拼音？",
   "placeholder_roles":["protagonist"],
   "options":["bái sè","bāi sè","bái sē","bǎi sè"],
   "answer":0,"correct_answer":"bái sè"},
  {"id":"CHN111","category":"汉语拼音","difficulty":"P1-P2",
   "template":"{CHARACTER_0}画了一个「红色」的苹果，下列哪个是「红色」的正确拼音？",
   "placeholder_roles":["protagonist"],
   "options":["hóng sè","hōng sè","hóng sē","hǒng sè"],
   "answer":0,"correct_answer":"hóng sè"},
  {"id":"CHN112","category":"汉语拼音","difficulty":"P1-P2",
   "template":"{CHARACTER_0}每天早上喜欢「跑步」，下列哪个是「跑步」的正确拼音？",
   "placeholder_roles":["protagonist"],
   "options":["pǎo bù","páo bù","pǎo bú","pāo bù"],
   "answer":0,"correct_answer":"pǎo bù"},
  {"id":"CHN113","category":"汉语拼音","difficulty":"P1-P2",
   "template":"{CHARACTER_0}学会了「游泳」，下列哪个是「游泳」的正确拼音？",
   "placeholder_roles":["protagonist"],
   "options":["yóu yǒng","yōu yǒng","yóu yōng","yǒu yǒng"],
   "answer":0,"correct_answer":"yóu yǒng"},
  {"id":"CHN114","category":"汉语拼音","difficulty":"P1-P2",
   "template":"{CHARACTER_0}喜欢「唱歌」，下列哪个是「唱歌」的正确拼音？",
   "placeholder_roles":["protagonist"],
   "options":["chàng gē","cháng gē","chàng gé","chāng gē"],
   "answer":0,"correct_answer":"chàng gē"},
  {"id":"CHN115","category":"汉语拼音","difficulty":"P1-P2",
   "template":"{CHARACTER_0}学会了「跳舞」，下列哪个是「跳舞」的正确拼音？",
   "placeholder_roles":["protagonist"],
   "options":["tiào wǔ","tiāo wǔ","tiào wū","tiǎo wǔ"],
   "answer":0,"correct_answer":"tiào wǔ"},
  {"id":"CHN116","category":"汉语拼音","difficulty":"P1-P2",
   "template":"{CHARACTER_0}收到礼物，感到非常「高兴」，下列哪个是「高兴」的正确拼音？",
   "placeholder_roles":["protagonist"],
   "options":["gāo xìng","gáo xìng","gāo xíng","gǎo xìng"],
   "answer":0,"correct_answer":"gāo xìng"},
  {"id":"CHN117","category":"汉语拼音","difficulty":"P1-P2",
   "template":"今天是{CHARACTER_0}的「生日」，下列哪个是「生日」的正确拼音？",
   "placeholder_roles":["protagonist"],
   "options":["shēng rì","shéng rì","shēng rí","shěng rì"],
   "answer":0,"correct_answer":"shēng rì"},
  {"id":"CHN118","category":"汉语拼音","difficulty":"P1-P2",
   "template":"{CHARACTER_0}有一个可爱的「弟弟」，下列哪个是「弟弟」的正确拼音？",
   "placeholder_roles":["protagonist"],
   "options":["dì di","dí di","dì dì","dī di"],
   "answer":0,"correct_answer":"dì di"},
  {"id":"CHN119","category":"汉语拼音","difficulty":"P1-P2",
   "template":"{CHARACTER_0}的「姐姐」非常温柔，下列哪个是「姐姐」的正确拼音？",
   "placeholder_roles":["protagonist"],
   "options":["jiě jie","jiē jie","jiě jiě","jié jie"],
   "answer":0,"correct_answer":"jiě jie"},
  {"id":"CHN120","category":"汉语拼音","difficulty":"P1-P2",
   "template":"{CHARACTER_0}的「哥哥」很爱护弟妹，下列哪个是「哥哥」的正确拼音？",
   "placeholder_roles":["protagonist"],
   "options":["gē ge","gé ge","gē gě","gě ge"],
   "answer":0,"correct_answer":"gē ge"},
  {"id":"CHN121","category":"汉语拼音","difficulty":"P1-P2",
   "template":"{CHARACTER_0}和「妹妹」一起玩，下列哪个是「妹妹」的正确拼音？",
   "placeholder_roles":["protagonist"],
   "options":["mèi mei","méi mei","mèi mèi","mēi mei"],
   "answer":0,"correct_answer":"mèi mei"},
  {"id":"CHN122","category":"汉语拼音","difficulty":"P1-P2",
   "template":"{CHARACTER_0}很尊敬「爷爷」，下列哪个是「爷爷」的正确拼音？",
   "placeholder_roles":["protagonist"],
   "options":["yé ye","yē ye","yé yé","yě ye"],
   "answer":0,"correct_answer":"yé ye"},
  {"id":"CHN123","category":"汉语拼音","difficulty":"P1-P2",
   "template":"{CHARACTER_0}每天帮「奶奶」做家务，下列哪个是「奶奶」的正确拼音？",
   "placeholder_roles":["protagonist"],
   "options":["nǎi nai","nài nai","nǎi nǎi","nāi nai"],
   "answer":0,"correct_answer":"nǎi nai"},
  {"id":"CHN124","category":"汉语拼音","difficulty":"P1-P2",
   "template":"天空中有一个大大的「太阳」，下列哪个是「太阳」的正确拼音？",
   "placeholder_roles":[],
   "options":["tài yáng","tāi yáng","tài yāng","tǎi yáng"],
   "answer":0,"correct_answer":"tài yáng"},
  {"id":"CHN125","category":"汉语拼音","difficulty":"P1-P2",
   "template":"夜晚，天空中出现了圆圆的「月亮」，下列哪个是「月亮」的正确拼音？",
   "placeholder_roles":[],
   "options":["yuè liang","yuē liang","yuè liáng","yué liang"],
   "answer":0,"correct_answer":"yuè liang"},
  {"id":"CHN126","category":"汉语拼音","difficulty":"P1-P2",
   "template":"夜晚的天空有无数闪亮的「星星」，下列哪个是「星星」的正确拼音？",
   "placeholder_roles":[],
   "options":["xīng xing","xíng xing","xīng xīng","xǐng xing"],
   "answer":0,"correct_answer":"xīng xing"},
  {"id":"CHN127","category":"汉语拼音","difficulty":"P1-P2",
   "template":"{CHARACTER_0}养了一只可爱的「小狗」，下列哪个是「小狗」的正确拼音？",
   "placeholder_roles":["protagonist"],
   "options":["xiǎo gǒu","xiāo gǒu","xiǎo gōu","xiào gǒu"],
   "answer":0,"correct_answer":"xiǎo gǒu"},
  {"id":"CHN128","category":"汉语拼音","difficulty":"P1-P2",
   "template":"{CHARACTER_0}家里有一只「小猫」，下列哪个是「小猫」的正确拼音？",
   "placeholder_roles":["protagonist"],
   "options":["xiǎo māo","xiāo māo","xiǎo máo","xiào māo"],
   "answer":0,"correct_answer":"xiǎo māo"},
  {"id":"CHN129","category":"汉语拼音","difficulty":"P1-P2",
   "template":"{CHARACTER_0}很爱「家人」，下列哪个是「家人」的正确拼音？",
   "placeholder_roles":["protagonist"],
   "options":["jiā rén","jiǎ rén","jiā rěn","jiá rén"],
   "answer":0,"correct_answer":"jiā rén"},
  {"id":"CHN130","category":"汉语拼音","difficulty":"P1-P2",
   "template":"{CHARACTER_0}向老师打招呼「你好」，下列哪个是「你好」的正确拼音？",
   "placeholder_roles":["protagonist"],
   "options":["nǐ hǎo","nī hǎo","nǐ hāo","ní hǎo"],
   "answer":0,"correct_answer":"nǐ hǎo"},
]

# ──────────────────────────────────────────────
# 汉语拼音  P3-P4  CHN131–CHN156  (26 questions)
# ──────────────────────────────────────────────
questions += [
  {"id":"CHN131","category":"汉语拼音","difficulty":"P3-P4",
   "template":"{CHARACTER_0}很「努力」地学习，下列哪个是「努力」的正确拼音？",
   "placeholder_roles":["protagonist"],
   "options":["nǔ lì","nú lì","nǔ lí","nū lì"],
   "answer":0,"correct_answer":"nǔ lì"},
  {"id":"CHN132","category":"汉语拼音","difficulty":"P3-P4",
   "template":"{CHARACTER_0}帮妈妈「整理」房间，下列哪个是「整理」的正确拼音？",
   "placeholder_roles":["protagonist"],
   "options":["zhěng lǐ","zhēng lǐ","zhěng lí","zhèng lǐ"],
   "answer":0,"correct_answer":"zhěng lǐ"},
  {"id":"CHN133","category":"汉语拼音","difficulty":"P3-P4",
   "template":"{CHARACTER_0}经常「帮助」同学，下列哪个是「帮助」的正确拼音？",
   "placeholder_roles":["protagonist"],
   "options":["bāng zhù","bǎng zhù","bāng zhú","báng zhù"],
   "answer":0,"correct_answer":"bāng zhù"},
  {"id":"CHN134","category":"汉语拼音","difficulty":"P3-P4",
   "template":"{CHARACTER_0}「认真」地做作业，下列哪个是「认真」的正确拼音？",
   "placeholder_roles":["protagonist"],
   "options":["rèn zhēn","rén zhēn","rèn zhén","rěn zhēn"],
   "answer":0,"correct_answer":"rèn zhēn"},
  {"id":"CHN135","category":"汉语拼音","difficulty":"P3-P4",
   "template":"{CHARACTER_0}终于「完成」了作业，下列哪个是「完成」的正确拼音？",
   "placeholder_roles":["protagonist"],
   "options":["wán chéng","wān chéng","wán chēng","wǎn chéng"],
   "answer":0,"correct_answer":"wán chéng"},
  {"id":"CHN136","category":"汉语拼音","difficulty":"P3-P4",
   "template":"{CHARACTER_0}报名「参加」学校的比赛，下列哪个是「参加」的正确拼音？",
   "placeholder_roles":["protagonist"],
   "options":["cān jiā","cán jiā","cān jiǎ","cān jiá"],
   "answer":0,"correct_answer":"cān jiā"},
  {"id":"CHN137","category":"汉语拼音","difficulty":"P3-P4",
   "template":"{CHARACTER_0}在「比赛」中获得了第一名，下列哪个是「比赛」的正确拼音？",
   "placeholder_roles":["protagonist"],
   "options":["bǐ sài","bí sài","bǐ sāi","bì sài"],
   "answer":0,"correct_answer":"bǐ sài"},
  {"id":"CHN138","category":"汉语拼音","difficulty":"P3-P4",
   "template":"{CHARACTER_0}「赢得」了冠军，下列哪个是「赢得」的正确拼音？",
   "placeholder_roles":["protagonist"],
   "options":["yíng dé","yīng dé","yíng dě","yǐng dé"],
   "answer":0,"correct_answer":"yíng dé"},
  {"id":"CHN139","category":"汉语拼音","difficulty":"P3-P4",
   "template":"{CHARACTER_0}在「操场」上玩耍，下列哪个是「操场」的正确拼音？",
   "placeholder_roles":["protagonist"],
   "options":["cāo chǎng","cáo chǎng","cāo chāng","cǎo chǎng"],
   "answer":0,"correct_answer":"cāo chǎng"},
  {"id":"CHN140","category":"汉语拼音","difficulty":"P3-P4",
   "template":"{CHARACTER_0}喜欢上「音乐」课，下列哪个是「音乐」的正确拼音？",
   "placeholder_roles":["protagonist"],
   "options":["yīn yuè","yín yuè","yīn yuē","yǐn yuè"],
   "answer":0,"correct_answer":"yīn yuè"},
  {"id":"CHN141","category":"汉语拼音","difficulty":"P3-P4",
   "template":"{CHARACTER_0}擅长「美术」，下列哪个是「美术」的正确拼音？",
   "placeholder_roles":["protagonist"],
   "options":["měi shù","méi shù","měi shū","mèi shù"],
   "answer":0,"correct_answer":"měi shù"},
  {"id":"CHN142","category":"汉语拼音","difficulty":"P3-P4",
   "template":"{CHARACTER_0}最喜欢「体育」课，下列哪个是「体育」的正确拼音？",
   "placeholder_roles":["protagonist"],
   "options":["tǐ yù","tī yù","tǐ yū","tí yù"],
   "answer":0,"correct_answer":"tǐ yù"},
  {"id":"CHN143","category":"汉语拼音","difficulty":"P3-P4",
   "template":"{CHARACTER_0}在课上学习「自然」科学，下列哪个是「自然」的正确拼音？",
   "placeholder_roles":["protagonist"],
   "options":["zì rán","zī rán","zì rǎn","zhì rán"],
   "answer":0,"correct_answer":"zì rán"},
  {"id":"CHN144","category":"汉语拼音","difficulty":"P3-P4",
   "template":"{CHARACTER_0}对「科学」很感兴趣，下列哪个是「科学」的正确拼音？",
   "placeholder_roles":["protagonist"],
   "options":["kē xué","ké xué","kē xuē","kě xué"],
   "answer":0,"correct_answer":"kē xué"},
  {"id":"CHN145","category":"汉语拼音","difficulty":"P3-P4",
   "template":"{CHARACTER_0}「数学」考试得了满分，下列哪个是「数学」的正确拼音？",
   "placeholder_roles":["protagonist"],
   "options":["shù xué","shū xué","shù xuě","shú xué"],
   "answer":0,"correct_answer":"shù xué"},
  {"id":"CHN146","category":"汉语拼音","difficulty":"P3-P4",
   "template":"{CHARACTER_0}喜欢「语文」课，下列哪个是「语文」的正确拼音？",
   "placeholder_roles":["protagonist"],
   "options":["yǔ wén","yū wén","yǔ wēn","yú wén"],
   "answer":0,"correct_answer":"yǔ wén"},
  {"id":"CHN147","category":"汉语拼音","difficulty":"P3-P4",
   "template":"{CHARACTER_0}「英语」说得很流利，下列哪个是「英语」的正确拼音？",
   "placeholder_roles":["protagonist"],
   "options":["yīng yǔ","yíng yǔ","yīng yū","yǐng yǔ"],
   "answer":0,"correct_answer":"yīng yǔ"},
  {"id":"CHN148","category":"汉语拼音","difficulty":"P3-P4",
   "template":"{CHARACTER_0}每天在学校「食堂」吃午餐，下列哪个是「食堂」的正确拼音？",
   "placeholder_roles":["protagonist"],
   "options":["shí táng","shī táng","shí tāng","shì táng"],
   "answer":0,"correct_answer":"shí táng"},
  {"id":"CHN149","category":"汉语拼音","difficulty":"P3-P4",
   "template":"{CHARACTER_0}和「同学」们一起做作业，下列哪个是「同学」的正确拼音？",
   "placeholder_roles":["protagonist"],
   "options":["tóng xué","tōng xué","tóng xuě","tǒng xué"],
   "answer":0,"correct_answer":"tóng xué"},
  {"id":"CHN150","category":"汉语拼音","difficulty":"P3-P4",
   "template":"{CHARACTER_0}大声朗读「课文」，下列哪个是「课文」的正确拼音？",
   "placeholder_roles":["protagonist"],
   "options":["kè wén","ké wén","kè wēn","kě wén"],
   "answer":0,"correct_answer":"kè wén"},
  {"id":"CHN151","category":"汉语拼音","difficulty":"P3-P4",
   "template":"{CHARACTER_0}每天做拼音「练习」，下列哪个是「练习」的正确拼音？",
   "placeholder_roles":["protagonist"],
   "options":["liàn xí","liān xí","liàn xī","lián xí"],
   "answer":0,"correct_answer":"liàn xí"},
  {"id":"CHN152","category":"汉语拼音","difficulty":"P3-P4",
   "template":"{CHARACTER_0}按时完成「作业」，下列哪个是「作业」的正确拼音？",
   "placeholder_roles":["protagonist"],
   "options":["zuò yè","zuō yè","zuò yē","zuǒ yè"],
   "answer":0,"correct_answer":"zuò yè"},
  {"id":"CHN153","category":"汉语拼音","difficulty":"P3-P4",
   "template":"老师在「黑板」上写字，下列哪个是「黑板」的正确拼音？",
   "placeholder_roles":[],
   "options":["hēi bǎn","héi bǎn","hēi bān","hěi bǎn"],
   "answer":0,"correct_answer":"hēi bǎn"},
  {"id":"CHN154","category":"汉语拼音","difficulty":"P3-P4",
   "template":"{CHARACTER_0}用「铅笔」画画，下列哪个是「铅笔」的正确拼音？",
   "placeholder_roles":["protagonist"],
   "options":["qiān bǐ","qiǎn bǐ","qiān bī","qián bǐ"],
   "answer":0,"correct_answer":"qiān bǐ"},
  {"id":"CHN155","category":"汉语拼音","difficulty":"P3-P4",
   "template":"{CHARACTER_0}每天「阅读」一小时，下列哪个是「阅读」的正确拼音？",
   "placeholder_roles":["protagonist"],
   "options":["yuè dú","yuē dú","yuè dū","yué dú"],
   "answer":0,"correct_answer":"yuè dú"},
  {"id":"CHN156","category":"汉语拼音","difficulty":"P3-P4",
   "template":"{CHARACTER_0}整理好「书包」准备上学，下列哪个是「书包」的正确拼音？",
   "placeholder_roles":["protagonist"],
   "options":["shū bāo","shú bāo","shū báo","shǔ bāo"],
   "answer":0,"correct_answer":"shū bāo"},
]

# ──────────────────────────────────────────────
# 汉语拼音  P5-P6  CHN157–CHN182  (26 questions)
# ──────────────────────────────────────────────
questions += [
  {"id":"CHN157","category":"汉语拼音","difficulty":"P5-P6",
   "template":"{CHARACTER_0}「坚持」不懈，终于成功，下列哪个是「坚持」的正确拼音？",
   "placeholder_roles":["protagonist"],
   "options":["jiān chí","jiǎn chí","jiān chī","jiàn chí"],
   "answer":0,"correct_answer":"jiān chí"},
  {"id":"CHN158","category":"汉语拼音","difficulty":"P5-P6",
   "template":"{CHARACTER_0}凭着「毅力」克服了重重困难，下列哪个是「毅力」的正确拼音？",
   "placeholder_roles":["protagonist"],
   "options":["yì lì","yí lì","yì lī","yǐ lì"],
   "answer":0,"correct_answer":"yì lì"},
  {"id":"CHN159","category":"汉语拼音","difficulty":"P5-P6",
   "template":"{CHARACTER_0}为人「谦虚」，不炫耀成绩，下列哪个是「谦虚」的正确拼音？",
   "placeholder_roles":["protagonist"],
   "options":["qiān xū","qiǎn xū","qiān xú","qián xū"],
   "answer":0,"correct_answer":"qiān xū"},
  {"id":"CHN160","category":"汉语拼音","difficulty":"P5-P6",
   "template":"{CHARACTER_0}待人「宽容」，从不斤斤计较，下列哪个是「宽容」的正确拼音？",
   "placeholder_roles":["protagonist"],
   "options":["kuān róng","kuǎn róng","kuān rōng","kuán róng"],
   "answer":0,"correct_answer":"kuān róng"},
  {"id":"CHN161","category":"汉语拼音","difficulty":"P5-P6",
   "template":"{CHARACTER_0}对帮助过自己的人深感「感激」，下列哪个是「感激」的正确拼音？",
   "placeholder_roles":["protagonist"],
   "options":["gǎn jī","gān jī","gǎn jí","gàn jī"],
   "answer":0,"correct_answer":"gǎn jī"},
  {"id":"CHN162","category":"汉语拼音","difficulty":"P5-P6",
   "template":"老师不断「鼓励」{CHARACTER_0}，下列哪个是「鼓励」的正确拼音？",
   "placeholder_roles":["protagonist"],
   "options":["gǔ lì","gū lì","gǔ lí","gú lì"],
   "answer":0,"correct_answer":"gǔ lì"},
  {"id":"CHN163","category":"汉语拼音","difficulty":"P5-P6",
   "template":"{CHARACTER_0}取得了很多「成就」，下列哪个是「成就」的正确拼音？",
   "placeholder_roles":["protagonist"],
   "options":["chéng jiù","chēng jiù","chéng jiū","chèng jiù"],
   "answer":0,"correct_answer":"chéng jiù"},
  {"id":"CHN164","category":"汉语拼音","difficulty":"P5-P6",
   "template":"{CHARACTER_0}勇于接受「挑战」，下列哪个是「挑战」的正确拼音？",
   "placeholder_roles":["protagonist"],
   "options":["tiǎo zhàn","tiāo zhàn","tiǎo zhān","tiào zhàn"],
   "answer":0,"correct_answer":"tiǎo zhàn"},
  {"id":"CHN165","category":"汉语拼音","difficulty":"P5-P6",
   "template":"{CHARACTER_0}认为保护环境是每个人的「责任」，下列哪个是「责任」的正确拼音？",
   "placeholder_roles":["protagonist"],
   "options":["zé rèn","zē rèn","zé rén","zhé rèn"],
   "answer":0,"correct_answer":"zé rèn"},
  {"id":"CHN166","category":"汉语拼音","difficulty":"P5-P6",
   "template":"朋友之间应该互相「信任」，下列哪个是「信任」的正确拼音？",
   "placeholder_roles":[],
   "options":["xìn rèn","xín rèn","xìn rén","xīn rèn"],
   "answer":0,"correct_answer":"xìn rèn"},
  {"id":"CHN167","category":"汉语拼音","difficulty":"P5-P6",
   "template":"{CHARACTER_0}认为「合作」精神非常重要，下列哪个是「合作」的正确拼音？",
   "placeholder_roles":["protagonist"],
   "options":["hé zuò","hē zuò","hé zuō","hě zuò"],
   "answer":0,"correct_answer":"hé zuò"},
  {"id":"CHN168","category":"汉语拼音","difficulty":"P5-P6",
   "template":"{CHARACTER_0}教导我们要「尊重」长辈，下列哪个是「尊重」的正确拼音？",
   "placeholder_roles":["protagonist"],
   "options":["zūn zhòng","zún zhòng","zūn zhōng","zǔn zhòng"],
   "answer":0,"correct_answer":"zūn zhòng"},
  {"id":"CHN169","category":"汉语拼音","difficulty":"P5-P6",
   "template":"{CHARACTER_0}心存「感恩」，懂得珍惜，下列哪个是「感恩」的正确拼音？",
   "placeholder_roles":["protagonist"],
   "options":["gǎn ēn","gān ēn","gǎn én","gàn ēn"],
   "answer":0,"correct_answer":"gǎn ēn"},
  {"id":"CHN170","category":"汉语拼音","difficulty":"P5-P6",
   "template":"老师为学生默默「奉献」，下列哪个是「奉献」的正确拼音？",
   "placeholder_roles":[],
   "options":["fèng xiàn","féng xiàn","fèng xiǎn","fěng xiàn"],
   "answer":0,"correct_answer":"fèng xiàn"},
  {"id":"CHN171","category":"汉语拼音","difficulty":"P5-P6",
   "template":"{CHARACTER_0}有着高尚的「品德」，下列哪个是「品德」的正确拼音？",
   "placeholder_roles":["protagonist"],
   "options":["pǐn dé","pín dé","pǐn dě","pīn dé"],
   "answer":0,"correct_answer":"pǐn dé"},
  {"id":"CHN172","category":"汉语拼音","difficulty":"P5-P6",
   "template":"我们「应该」尊重他人，下列哪个是「应该」的正确拼音？",
   "placeholder_roles":[],
   "options":["yīng gāi","yíng gāi","yīng gǎi","yǐng gāi"],
   "answer":0,"correct_answer":"yīng gāi"},
  {"id":"CHN173","category":"汉语拼音","difficulty":"P5-P6",
   "template":"{CHARACTER_0}找出了题目的「答案」，下列哪个是「答案」的正确拼音？",
   "placeholder_roles":["protagonist"],
   "options":["dá àn","dā àn","dá ān","dǎ àn"],
   "answer":0,"correct_answer":"dá àn"},
  {"id":"CHN174","category":"汉语拼音","difficulty":"P5-P6",
   "template":"{CHARACTER_0}明白诚实是非常「重要」的，下列哪个是「重要」的正确拼音？",
   "placeholder_roles":["protagonist"],
   "options":["zhòng yào","zhōng yào","zhòng yǎo","zhóng yào"],
   "answer":0,"correct_answer":"zhòng yào"},
  {"id":"CHN175","category":"汉语拼音","difficulty":"P5-P6",
   "template":"{CHARACTER_0}思考这件事的「意义」，下列哪个是「意义」的正确拼音？",
   "placeholder_roles":["protagonist"],
   "options":["yì yì","yí yì","yì yī","yǐ yì"],
   "answer":0,"correct_answer":"yì yì"},
  {"id":"CHN176","category":"汉语拼音","difficulty":"P5-P6",
   "template":"父母对{CHARACTER_0}有很大的「影响」，下列哪个是「影响」的正确拼音？",
   "placeholder_roles":["protagonist"],
   "options":["yǐng xiǎng","yīng xiǎng","yǐng xiāng","yìng xiǎng"],
   "answer":0,"correct_answer":"yǐng xiǎng"},
  {"id":"CHN177","category":"汉语拼音","difficulty":"P5-P6",
   "template":"{CHARACTER_0}学习「态度」认真，下列哪个是「态度」的正确拼音？",
   "placeholder_roles":["protagonist"],
   "options":["tài dù","tǎi dù","tài dū","tāi dù"],
   "answer":0,"correct_answer":"tài dù"},
  {"id":"CHN178","category":"汉语拼音","difficulty":"P5-P6",
   "template":"我们要保护自己的生活「环境」，下列哪个是「环境」的正确拼音？",
   "placeholder_roles":[],
   "options":["huán jìng","huān jìng","huán jǐng","huǎn jìng"],
   "answer":0,"correct_answer":"huán jìng"},
  {"id":"CHN179","category":"汉语拼音","difficulty":"P5-P6",
   "template":"{CHARACTER_0}积极「保护」濒危动物，下列哪个是「保护」的正确拼音？",
   "placeholder_roles":["protagonist"],
   "options":["bǎo hù","báo hù","bǎo hú","bào hù"],
   "answer":0,"correct_answer":"bǎo hù"},
  {"id":"CHN180","category":"汉语拼音","difficulty":"P5-P6",
   "template":"社会不断「发展」，生活越来越好，下列哪个是「发展」的正确拼音？",
   "placeholder_roles":[],
   "options":["fā zhǎn","fǎ zhǎn","fā zhàn","fá zhǎn"],
   "answer":0,"correct_answer":"fā zhǎn"},
  {"id":"CHN181","category":"汉语拼音","difficulty":"P5-P6",
   "template":"{CHARACTER_0}热爱中华「文化」，下列哪个是「文化」的正确拼音？",
   "placeholder_roles":["protagonist"],
   "options":["wén huà","wēn huà","wén huā","wǔ huà"],
   "answer":0,"correct_answer":"wén huà"},
  {"id":"CHN182","category":"汉语拼音","difficulty":"P5-P6",
   "template":"{CHARACTER_0}懂得「珍惜」时光，下列哪个是「珍惜」的正确拼音？",
   "placeholder_roles":["protagonist"],
   "options":["zhēn xī","zhén xī","zhēn xí","zhěn xī"],
   "answer":0,"correct_answer":"zhēn xī"},
]

# ──────────────────────────────────────────────
# 汉语拼音  PSLE  CHN183–CHN191  (9 questions)
# ──────────────────────────────────────────────
questions += [
  {"id":"CHN183","category":"汉语拼音","difficulty":"PSLE",
   "template":"{CHARACTER_0}记住了「勤俭节约」这个成语，下列哪个是「勤俭节约」的正确拼音？",
   "placeholder_roles":["protagonist"],
   "options":["qín jiǎn jié yuē","qīn jiǎn jié yuē","qín jiān jié yuē","qín jiǎn jiē yuē"],
   "answer":0,"correct_answer":"qín jiǎn jié yuē"},
  {"id":"CHN184","category":"汉语拼音","difficulty":"PSLE",
   "template":"{CHARACTER_0}以「坚韧不拔」的精神面对挑战，下列哪个是「坚韧不拔」的正确拼音？",
   "placeholder_roles":["protagonist"],
   "options":["jiān rèn bù bá","jiǎn rèn bù bá","jiān rén bù bá","jiān rèn bú bá"],
   "answer":0,"correct_answer":"jiān rèn bù bá"},
  {"id":"CHN185","category":"汉语拼音","difficulty":"PSLE",
   "template":"{CHARACTER_0}「持之以恒」地练习，终于成功，下列哪个是「持之以恒」的正确拼音？",
   "placeholder_roles":["protagonist"],
   "options":["chí zhī yǐ héng","chī zhī yǐ héng","chí zhí yǐ héng","chí zhī yì héng"],
   "answer":0,"correct_answer":"chí zhī yǐ héng"},
  {"id":"CHN186","category":"汉语拼音","difficulty":"PSLE",
   "template":"{CHARACTER_0}为了备考「废寝忘食」地复习，下列哪个是「废寝忘食」的正确拼音？",
   "placeholder_roles":["protagonist"],
   "options":["fèi qǐn wàng shí","féi qǐn wàng shí","fèi qín wàng shí","fèi qǐn wǎng shí"],
   "answer":0,"correct_answer":"fèi qǐn wàng shí"},
  {"id":"CHN187","category":"汉语拼音","difficulty":"PSLE",
   "template":"{CHARACTER_0}做事「一丝不苟」，非常仔细，下列哪个是「一丝不苟」的正确拼音？",
   "placeholder_roles":["protagonist"],
   "options":["yī sī bù gǒu","yī sí bù gǒu","yī sī bú gǒu","yī sī bù gōu"],
   "answer":0,"correct_answer":"yī sī bù gǒu"},
  {"id":"CHN188","category":"汉语拼音","difficulty":"PSLE",
   "template":"{CHARACTER_0}凡事「精益求精」，力求完美，下列哪个是「精益求精」的正确拼音？",
   "placeholder_roles":["protagonist"],
   "options":["jīng yì qiú jīng","jíng yì qiú jīng","jīng yí qiú jīng","jīng yì qiū jīng"],
   "answer":0,"correct_answer":"jīng yì qiú jīng"},
  {"id":"CHN189","category":"汉语拼音","difficulty":"PSLE",
   "template":"老师称赞{CHARACTER_0}「博学多才」，下列哪个是「博学多才」的正确拼音？",
   "placeholder_roles":["protagonist"],
   "options":["bó xué duō cái","bō xué duō cái","bó xuě duō cái","bó xué duǒ cái"],
   "answer":0,"correct_answer":"bó xué duō cái"},
  {"id":"CHN190","category":"汉语拼音","difficulty":"PSLE",
   "template":"{CHARACTER_0}「勤勤恳恳」地工作，赢得大家的尊敬，下列哪个是「勤勤恳恳」的正确拼音？",
   "placeholder_roles":["protagonist"],
   "options":["qín qín kěn kěn","qīn qín kěn kěn","qín qín kēn kěn","qín qín kěn kén"],
   "answer":0,"correct_answer":"qín qín kěn kěn"},
  {"id":"CHN191","category":"汉语拼音","difficulty":"PSLE",
   "template":"{CHARACTER_0}有能力「克服困难」，下列哪个是「克服困难」的正确拼音？",
   "placeholder_roles":["protagonist"],
   "options":["kè fú kùn nán","kě fú kùn nán","kè fū kùn nán","kè fú kǔn nán"],
   "answer":0,"correct_answer":"kè fú kùn nán"},
]

# ──────────────────────────────────────────────
# 词汇  P1-P2  CHN192–CHN215  (24 questions)
# ──────────────────────────────────────────────
questions += [
  {"id":"CHN192","category":"词汇","difficulty":"P1-P2",
   "template":"选出与「伤心」意思相近的词语。（{CHARACTER_0}今天感到很伤心。）",
   "placeholder_roles":["protagonist"],
   "options":["难过","高兴","开心","快乐"],
   "answer":0,"correct_answer":"难过"},
  {"id":"CHN193","category":"词汇","difficulty":"P1-P2",
   "template":"{CHARACTER_0}问：「快」的反义词是什么？",
   "placeholder_roles":["protagonist"],
   "options":["慢","高","大","多"],
   "answer":0,"correct_answer":"慢"},
  {"id":"CHN194","category":"词汇","difficulty":"P1-P2",
   "template":"{CHARACTER_0}在学量词：一______花",
   "placeholder_roles":["protagonist"],
   "options":["朵","棵","条","个"],
   "answer":0,"correct_answer":"朵"},
  {"id":"CHN195","category":"词汇","difficulty":"P1-P2",
   "template":"{CHARACTER_0}在学量词：一______鱼",
   "placeholder_roles":["protagonist"],
   "options":["条","只","个","匹"],
   "answer":0,"correct_answer":"条"},
  {"id":"CHN196","category":"词汇","difficulty":"P1-P2",
   "template":"下面哪个词语可以填入句子：今天天气很______，大家都汗流浃背。",
   "placeholder_roles":[],
   "options":["热","冷","凉","暖"],
   "answer":0,"correct_answer":"热"},
  {"id":"CHN197","category":"词汇","difficulty":"P1-P2",
   "template":"{CHARACTER_0}问：「多」的反义词是什么？",
   "placeholder_roles":["protagonist"],
   "options":["少","小","矮","短"],
   "answer":0,"correct_answer":"少"},
  {"id":"CHN198","category":"词汇","difficulty":"P1-P2",
   "template":"{CHARACTER_0}在学量词：一______树",
   "placeholder_roles":["protagonist"],
   "options":["棵","条","块","朵"],
   "answer":0,"correct_answer":"棵"},
  {"id":"CHN199","category":"词汇","difficulty":"P1-P2",
   "template":"{CHARACTER_0}问：「高」的反义词是什么？",
   "placeholder_roles":["protagonist"],
   "options":["矮","短","小","少"],
   "answer":0,"correct_answer":"矮"},
  {"id":"CHN200","category":"词汇","difficulty":"P1-P2",
   "template":"选出与「开心」意思相近的词语。（{CHARACTER_0}今天感到非常开心。）",
   "placeholder_roles":["protagonist"],
   "options":["快乐","伤心","生气","害怕"],
   "answer":0,"correct_answer":"快乐"},
  {"id":"CHN201","category":"词汇","difficulty":"P1-P2",
   "template":"{CHARACTER_0}在学量词：一______叶子",
   "placeholder_roles":["protagonist"],
   "options":["片","棵","朵","个"],
   "answer":0,"correct_answer":"片"},
  {"id":"CHN202","category":"词汇","difficulty":"P1-P2",
   "template":"{CHARACTER_0}问：「白」的反义词是什么？",
   "placeholder_roles":["protagonist"],
   "options":["黑","红","蓝","绿"],
   "answer":0,"correct_answer":"黑"},
  {"id":"CHN203","category":"词汇","difficulty":"P1-P2",
   "template":"下面哪个词语可以填入句子：爸爸______我们去公园玩。",
   "placeholder_roles":[],
   "options":["带","来","去","走"],
   "answer":0,"correct_answer":"带"},
  {"id":"CHN204","category":"词汇","difficulty":"P1-P2",
   "template":"{CHARACTER_0}在学量词：一______饭",
   "placeholder_roles":["protagonist"],
   "options":["碗","盘","杯","个"],
   "answer":0,"correct_answer":"碗"},
  {"id":"CHN205","category":"词汇","difficulty":"P1-P2",
   "template":"{CHARACTER_0}问：「新」的反义词是什么？",
   "placeholder_roles":["protagonist"],
   "options":["旧","坏","破","烂"],
   "answer":0,"correct_answer":"旧"},
  {"id":"CHN206","category":"词汇","difficulty":"P1-P2",
   "template":"下面哪个词语最适合填入句子：{CHARACTER_0}第一次骑自行车成功，觉得非常______。",
   "placeholder_roles":["protagonist"],
   "options":["开心","伤心","难过","害怕"],
   "answer":0,"correct_answer":"开心"},
  {"id":"CHN207","category":"词汇","difficulty":"P1-P2",
   "template":"{CHARACTER_0}在学量词：一______鞋",
   "placeholder_roles":["protagonist"],
   "options":["双","只","个","件"],
   "answer":0,"correct_answer":"双"},
  {"id":"CHN208","category":"词汇","difficulty":"P1-P2",
   "template":"{CHARACTER_0}问：「长」的反义词是什么？",
   "placeholder_roles":["protagonist"],
   "options":["短","矮","小","少"],
   "answer":0,"correct_answer":"短"},
  {"id":"CHN209","category":"词汇","difficulty":"P1-P2",
   "template":"下面哪个词语最适合填入句子：{CHARACTER_0}的房间非常______，东西都摆放整齐。",
   "placeholder_roles":["protagonist"],
   "options":["干净","脏乱","凌乱","杂乱"],
   "answer":0,"correct_answer":"干净"},
  {"id":"CHN210","category":"词汇","difficulty":"P1-P2",
   "template":"选出与「好看」意思相近的词语。（{CHARACTER_0}说这件衣服真好看。）",
   "placeholder_roles":["protagonist"],
   "options":["漂亮","丑陋","普通","简单"],
   "answer":0,"correct_answer":"漂亮"},
  {"id":"CHN211","category":"词汇","difficulty":"P1-P2",
   "template":"{CHARACTER_0}问：「干净」的反义词是什么？",
   "placeholder_roles":["protagonist"],
   "options":["脏","乱","臭","差"],
   "answer":0,"correct_answer":"脏"},
  {"id":"CHN212","category":"词汇","difficulty":"P1-P2",
   "template":"{CHARACTER_0}在学量词：一______水",
   "placeholder_roles":["protagonist"],
   "options":["杯","条","棵","块"],
   "answer":0,"correct_answer":"杯"},
  {"id":"CHN213","category":"词汇","difficulty":"P1-P2",
   "template":"下面哪个词语最适合填入句子：弟弟肚子______了，吵着要吃东西。",
   "placeholder_roles":[],
   "options":["饿","痛","冷","渴"],
   "answer":0,"correct_answer":"饿"},
  {"id":"CHN214","category":"词汇","difficulty":"P1-P2",
   "template":"{CHARACTER_0}问：「好」的反义词是什么？",
   "placeholder_roles":["protagonist"],
   "options":["坏","差","低","弱"],
   "answer":0,"correct_answer":"坏"},
  {"id":"CHN215","category":"词汇","difficulty":"P1-P2",
   "template":"{CHARACTER_0}在学量词：一______蛋糕",
   "placeholder_roles":["protagonist"],
   "options":["块","朵","条","棵"],
   "answer":0,"correct_answer":"块"},
]

# ──────────────────────────────────────────────
# 词汇  P3-P4  CHN216–CHN239  (24 questions)
# ──────────────────────────────────────────────
questions += [
  {"id":"CHN216","category":"词汇","difficulty":"P3-P4",
   "template":"选出与「担心」意思相近的词语。（{CHARACTER_0}很担心考试的成绩。）",
   "placeholder_roles":["protagonist"],
   "options":["忧虑","开心","平静","放心"],
   "answer":0,"correct_answer":"忧虑"},
  {"id":"CHN217","category":"词汇","difficulty":"P3-P4",
   "template":"{CHARACTER_0}问：「懒惰」的反义词是什么？",
   "placeholder_roles":["protagonist"],
   "options":["勤快","忙碌","努力","积极"],
   "answer":0,"correct_answer":"勤快"},
  {"id":"CHN218","category":"词汇","difficulty":"P3-P4",
   "template":"{CHARACTER_0}在学量词：一______歌",
   "placeholder_roles":["protagonist"],
   "options":["首","个","条","篇"],
   "answer":0,"correct_answer":"首"},
  {"id":"CHN219","category":"词汇","difficulty":"P3-P4",
   "template":"下面哪个词语最适合填入句子：比赛开始了，{CHARACTER_0}______地冲向终点。",
   "placeholder_roles":["protagonist"],
   "options":["奋力","懒散","随便","慢吞吞"],
   "answer":0,"correct_answer":"奋力"},
  {"id":"CHN220","category":"词汇","difficulty":"P3-P4",
   "template":"下面哪个句子中，「打」字的意思是「用电话联系」？",
   "placeholder_roles":[],
   "options":["他打电话给妈妈。","他打了一个球。","他打扫房间。","他打算去旅行。"],
   "answer":0,"correct_answer":"他打电话给妈妈。"},
  {"id":"CHN221","category":"词汇","difficulty":"P3-P4",
   "template":"选出与「平静」意思相近的词语。（{CHARACTER_0}的心情很平静。）",
   "placeholder_roles":["protagonist"],
   "options":["宁静","热闹","吵闹","紧张"],
   "answer":0,"correct_answer":"宁静"},
  {"id":"CHN222","category":"词汇","difficulty":"P3-P4",
   "template":"{CHARACTER_0}问：「骄傲」的反义词是什么？",
   "placeholder_roles":["protagonist"],
   "options":["谦虚","勤快","诚实","聪明"],
   "answer":0,"correct_answer":"谦虚"},
  {"id":"CHN223","category":"词汇","difficulty":"P3-P4",
   "template":"{CHARACTER_0}在学量词：一______诗",
   "placeholder_roles":["protagonist"],
   "options":["首","个","篇","张"],
   "answer":0,"correct_answer":"首"},
  {"id":"CHN224","category":"词汇","difficulty":"P3-P4",
   "template":"下面哪个词语最适合填入句子：他虽然跌倒了，但毫不______，继续向前跑。",
   "placeholder_roles":[],
   "options":["气馁","高兴","开心","放心"],
   "answer":0,"correct_answer":"气馁"},
  {"id":"CHN225","category":"词汇","difficulty":"P3-P4",
   "template":"下列词语中，哪一个是形容词（描述性词语）？",
   "placeholder_roles":[],
   "options":["美丽","跑步","老师","学校"],
   "answer":0,"correct_answer":"美丽"},
  {"id":"CHN226","category":"词汇","difficulty":"P3-P4",
   "template":"选出与「勇敢」意思相近的词语。（{CHARACTER_0}非常勇敢。）",
   "placeholder_roles":["protagonist"],
   "options":["大胆","胆小","懦弱","害怕"],
   "answer":0,"correct_answer":"大胆"},
  {"id":"CHN227","category":"词汇","difficulty":"P3-P4",
   "template":"{CHARACTER_0}问：「诚实」的反义词是什么？",
   "placeholder_roles":["protagonist"],
   "options":["虚假","伤心","快乐","勇敢"],
   "answer":0,"correct_answer":"虚假"},
  {"id":"CHN228","category":"词汇","difficulty":"P3-P4",
   "template":"{CHARACTER_0}在学量词：一______山",
   "placeholder_roles":["protagonist"],
   "options":["座","条","个","棵"],
   "answer":0,"correct_answer":"座"},
  {"id":"CHN229","category":"词汇","difficulty":"P3-P4",
   "template":"下面哪个词语最适合填入句子：妈妈告诫{CHARACTER_0}，做人要______，不能说谎。",
   "placeholder_roles":["protagonist"],
   "options":["诚实","聪明","高兴","勤快"],
   "answer":0,"correct_answer":"诚实"},
  {"id":"CHN230","category":"词汇","difficulty":"P3-P4",
   "template":"选出与「开始」意思相近的词语。（活动即将开始。）",
   "placeholder_roles":[],
   "options":["开端","结束","停止","完成"],
   "answer":0,"correct_answer":"开端"},
  {"id":"CHN231","category":"词汇","difficulty":"P3-P4",
   "template":"{CHARACTER_0}问：「坚强」的反义词是什么？",
   "placeholder_roles":["protagonist"],
   "options":["软弱","懒惰","聪明","平静"],
   "answer":0,"correct_answer":"软弱"},
  {"id":"CHN232","category":"词汇","difficulty":"P3-P4",
   "template":"{CHARACTER_0}在学量词：一______河",
   "placeholder_roles":["protagonist"],
   "options":["条","座","片","棵"],
   "answer":0,"correct_answer":"条"},
  {"id":"CHN233","category":"词汇","difficulty":"P3-P4",
   "template":"下面哪个句子中，「看」字的意思是「照顾、看守」？",
   "placeholder_roles":[],
   "options":["妈妈在家看弟弟。","他在看书。","他们去看电影。","老师看见了他。"],
   "answer":0,"correct_answer":"妈妈在家看弟弟。"},
  {"id":"CHN234","category":"词汇","difficulty":"P3-P4",
   "template":"选出与「努力」意思相近的词语。（{CHARACTER_0}学习很努力。）",
   "placeholder_roles":["protagonist"],
   "options":["勤奋","懒惰","散漫","轻松"],
   "answer":0,"correct_answer":"勤奋"},
  {"id":"CHN235","category":"词汇","difficulty":"P3-P4",
   "template":"{CHARACTER_0}问：「慷慨」的反义词是什么？",
   "placeholder_roles":["protagonist"],
   "options":["吝啬","懒惰","骄傲","虚假"],
   "answer":0,"correct_answer":"吝啬"},
  {"id":"CHN236","category":"词汇","difficulty":"P3-P4",
   "template":"下面哪个词语最适合填入句子：弟弟很______，经常把零用钱存起来。",
   "placeholder_roles":[],
   "options":["节俭","浪费","挥霍","奢侈"],
   "answer":0,"correct_answer":"节俭"},
  {"id":"CHN237","category":"词汇","difficulty":"P3-P4",
   "template":"{CHARACTER_0}在学量词：一______楼",
   "placeholder_roles":["protagonist"],
   "options":["栋","座","层","间"],
   "answer":0,"correct_answer":"栋"},
  {"id":"CHN238","category":"词汇","difficulty":"P3-P4",
   "template":"下列词语中，哪一个是动词（表示行动的词语）？",
   "placeholder_roles":[],
   "options":["奔跑","美丽","图书馆","朋友"],
   "answer":0,"correct_answer":"奔跑"},
  {"id":"CHN239","category":"词汇","difficulty":"P3-P4",
   "template":"选出与「寒冷」意思相近的词语。（今天天气十分寒冷。）",
   "placeholder_roles":[],
   "options":["冰凉","炎热","温暖","凉爽"],
   "answer":0,"correct_answer":"冰凉"},
]

# ──────────────────────────────────────────────
# 词汇  P5-P6  CHN240–CHN263  (24 questions)
# ──────────────────────────────────────────────
questions += [
  {"id":"CHN240","category":"词汇","difficulty":"P5-P6",
   "template":"选出与「坚强」意思相近的词语。（{CHARACTER_0}十分坚强。）",
   "placeholder_roles":["protagonist"],
   "options":["刚毅","软弱","懦弱","脆弱"],
   "answer":0,"correct_answer":"刚毅"},
  {"id":"CHN241","category":"词汇","difficulty":"P5-P6",
   "template":"{CHARACTER_0}问：「自私」的反义词是什么？",
   "placeholder_roles":["protagonist"],
   "options":["慷慨","勤快","诚实","聪明"],
   "answer":0,"correct_answer":"慷慨"},
  {"id":"CHN242","category":"词汇","difficulty":"P5-P6",
   "template":"选出与「感激」意思相近的词语。（{CHARACTER_0}对帮助他的人深感感激。）",
   "placeholder_roles":["protagonist"],
   "options":["感谢","怨恨","生气","厌恶"],
   "answer":0,"correct_answer":"感谢"},
  {"id":"CHN243","category":"词汇","difficulty":"P5-P6",
   "template":"{CHARACTER_0}问：「勇敢」的反义词是什么？",
   "placeholder_roles":["protagonist"],
   "options":["胆怯","懒惰","软弱","骄傲"],
   "answer":0,"correct_answer":"胆怯"},
  {"id":"CHN244","category":"词汇","difficulty":"P5-P6",
   "template":"下面哪个词语最适合填入句子：面对困难，{CHARACTER_0}从不轻易______，始终坚持到底。",
   "placeholder_roles":["protagonist"],
   "options":["妥协","努力","奋斗","坚持"],
   "answer":0,"correct_answer":"妥协"},
  {"id":"CHN245","category":"词汇","difficulty":"P5-P6",
   "template":"{CHARACTER_0}在学量词：一______飞机",
   "placeholder_roles":["protagonist"],
   "options":["架","辆","艘","匹"],
   "answer":0,"correct_answer":"架"},
  {"id":"CHN246","category":"词汇","difficulty":"P5-P6",
   "template":"选出与「谦逊」意思相近的词语。（{CHARACTER_0}为人谦逊，从不自夸。）",
   "placeholder_roles":["protagonist"],
   "options":["谦虚","骄傲","自满","傲慢"],
   "answer":0,"correct_answer":"谦虚"},
  {"id":"CHN247","category":"词汇","difficulty":"P5-P6",
   "template":"{CHARACTER_0}问：「乐观」的反义词是什么？",
   "placeholder_roles":["protagonist"],
   "options":["悲观","开心","快乐","消极"],
   "answer":0,"correct_answer":"悲观"},
  {"id":"CHN248","category":"词汇","difficulty":"P5-P6",
   "template":"下面哪个词语最适合填入句子：老师______{CHARACTER_0}，称赞他的作文写得非常好。",
   "placeholder_roles":["protagonist"],
   "options":["赞扬","批评","责备","惩罚"],
   "answer":0,"correct_answer":"赞扬"},
  {"id":"CHN249","category":"词汇","difficulty":"P5-P6",
   "template":"下列词语中，哪一个是名词（人、事物或地方的名称）？",
   "placeholder_roles":[],
   "options":["品德","勇敢","奔跑","认真"],
   "answer":0,"correct_answer":"品德"},
  {"id":"CHN250","category":"词汇","difficulty":"P5-P6",
   "template":"下面哪个词语最适合填入句子：「他______了一个快乐的生日。」",
   "placeholder_roles":[],
   "options":["度过","经过","通过","走过"],
   "answer":0,"correct_answer":"度过"},
  {"id":"CHN251","category":"词汇","difficulty":"P5-P6",
   "template":"{CHARACTER_0}在学量词：一______船",
   "placeholder_roles":["protagonist"],
   "options":["艘","架","辆","匹"],
   "answer":0,"correct_answer":"艘"},
  {"id":"CHN252","category":"词汇","difficulty":"P5-P6",
   "template":"选出与「宽容」意思相近的词语。（{CHARACTER_0}待人宽容，从不斤斤计较。）",
   "placeholder_roles":["protagonist"],
   "options":["包容","苛刻","严厉","冷漠"],
   "answer":0,"correct_answer":"包容"},
  {"id":"CHN253","category":"词汇","difficulty":"P5-P6",
   "template":"{CHARACTER_0}问：「奢侈」的反义词是什么？",
   "placeholder_roles":["protagonist"],
   "options":["节俭","昂贵","豪华","高贵"],
   "answer":0,"correct_answer":"节俭"},
  {"id":"CHN254","category":"词汇","difficulty":"P5-P6",
   "template":"下面哪个词语最适合填入句子：{CHARACTER_0}______地完成了比赛，成为大家学习的榜样。",
   "placeholder_roles":["protagonist"],
   "options":["顽强","软弱","轻易","随便"],
   "answer":0,"correct_answer":"顽强"},
  {"id":"CHN255","category":"词汇","difficulty":"P5-P6",
   "template":"选出与「聪慧」意思相近的词语。（老师称赞{CHARACTER_0}聪慧过人。）",
   "placeholder_roles":["protagonist"],
   "options":["睿智","愚笨","迟钝","糊涂"],
   "answer":0,"correct_answer":"睿智"},
  {"id":"CHN256","category":"词汇","difficulty":"P5-P6",
   "template":"{CHARACTER_0}问：「懒惰」的反义词是什么？",
   "placeholder_roles":["protagonist"],
   "options":["勤劳","聪明","努力","积极"],
   "answer":0,"correct_answer":"勤劳"},
  {"id":"CHN257","category":"词汇","difficulty":"P5-P6",
   "template":"「鼓励」的意思是什么？",
   "placeholder_roles":[],
   "options":["激励他人，使其振作向上","对别人进行批评","责备他人的过失","对他人表示同情"],
   "answer":0,"correct_answer":"激励他人，使其振作向上"},
  {"id":"CHN258","category":"词汇","difficulty":"P5-P6",
   "template":"{CHARACTER_0}在学量词：一______信",
   "placeholder_roles":["protagonist"],
   "options":["封","张","份","本"],
   "answer":0,"correct_answer":"封"},
  {"id":"CHN259","category":"词汇","difficulty":"P5-P6",
   "template":"选出与「憎恨」意思相近的词语。（{CHARACTER_0}对不公平的事感到憎恨。）",
   "placeholder_roles":["protagonist"],
   "options":["厌恶","喜爱","钦佩","感激"],
   "answer":0,"correct_answer":"厌恶"},
  {"id":"CHN260","category":"词汇","difficulty":"P5-P6",
   "template":"{CHARACTER_0}问：「诚信」的反义词是什么？",
   "placeholder_roles":["protagonist"],
   "options":["虚伪","诚实","正直","忠诚"],
   "answer":0,"correct_answer":"虚伪"},
  {"id":"CHN261","category":"词汇","difficulty":"P5-P6",
   "template":"下面哪个词语最适合填入句子：{CHARACTER_0}的精神令人______，大家纷纷向他学习。",
   "placeholder_roles":["protagonist"],
   "options":["敬佩","失望","害怕","厌恶"],
   "answer":0,"correct_answer":"敬佩"},
  {"id":"CHN262","category":"词汇","difficulty":"P5-P6",
   "template":"下列词语中，哪一个是形容词（描述性词语）？",
   "placeholder_roles":[],
   "options":["坚韧","奔跑","学校","老师"],
   "answer":0,"correct_answer":"坚韧"},
  {"id":"CHN263","category":"词汇","difficulty":"P5-P6",
   "template":"选出与「奉献」意思相近的词语。（老师为学生默默奉献。）",
   "placeholder_roles":[],
   "options":["付出","索取","占有","消耗"],
   "answer":0,"correct_answer":"付出"},
]

# ──────────────────────────────────────────────
# 词汇  PSLE  CHN264–CHN270  (7 questions)
# ──────────────────────────────────────────────
questions += [
  {"id":"CHN264","category":"词汇","difficulty":"PSLE",
   "template":"下面哪个词语最适合填入句子：{CHARACTER_0}做事______，从不马虎，因此深受老师赏识。",
   "placeholder_roles":["protagonist"],
   "options":["一丝不苟","漫不经心","马马虎虎","糊里糊涂"],
   "answer":0,"correct_answer":"一丝不苟"},
  {"id":"CHN265","category":"词汇","difficulty":"PSLE",
   "template":"{CHARACTER_0}问：「轻视」的反义词是什么？",
   "placeholder_roles":["protagonist"],
   "options":["重视","喜爱","尊重","欣赏"],
   "answer":0,"correct_answer":"重视"},
  {"id":"CHN266","category":"词汇","difficulty":"PSLE",
   "template":"「坚韧不拔」的意思是什么？",
   "placeholder_roles":[],
   "options":["意志坚定，不轻易放弃","聪明能干，勤奋努力","学识渊博，多才多艺","一心一意，专心致志"],
   "answer":0,"correct_answer":"意志坚定，不轻易放弃"},
  {"id":"CHN267","category":"词汇","difficulty":"PSLE",
   "template":"下面哪个词语最适合填入句子：奶奶每天早起晚睡，勤快地做家务，真是______。",
   "placeholder_roles":[],
   "options":["任劳任怨","好吃懒做","斤斤计较","得过且过"],
   "answer":0,"correct_answer":"任劳任怨"},
  {"id":"CHN268","category":"词汇","difficulty":"PSLE",
   "template":"选出与「废寝忘食」意思最相近的词语。",
   "placeholder_roles":[],
   "options":["孜孜不倦","三心二意","漫不经心","心不在焉"],
   "answer":0,"correct_answer":"孜孜不倦"},
  {"id":"CHN269","category":"词汇","difficulty":"PSLE",
   "template":"下面哪个句子中，「半途而废」的用法是正确的？",
   "placeholder_roles":[],
   "options":["他做事从不半途而废，总能坚持到底。","这条河半途而废地流入了大海。","他的心情半途而废，非常难过。","小明半途而废了一顿美食。"],
   "answer":0,"correct_answer":"他做事从不半途而废，总能坚持到底。"},
  {"id":"CHN270","category":"词汇","difficulty":"PSLE",
   "template":"「克己奉公」的意思是什么？",
   "placeholder_roles":[],
   "options":["克制私欲，以公众利益为先","努力学习，取得好成绩","帮助他人，无私奉献","遵纪守法，不违规"],
   "answer":0,"correct_answer":"克制私欲，以公众利益为先"},
]

# ── Validation ──
assert len(questions) == 166, f"Expected 166 questions, got {len(questions)}"
ids = [q["id"] for q in questions]
assert len(set(ids)) == len(ids), "Duplicate IDs found!"
for q in questions:
    assert q["answer"] == 0, f"{q['id']}: answer must be 0"
    assert q["options"][0] == q["correct_answer"], f"{q['id']}: first option must equal correct_answer"
    assert len(q["options"]) == 4, f"{q['id']}: must have 4 options"
    if "{CHARACTER_0}" in q["template"]:
        assert q["placeholder_roles"] == ["protagonist"], f"{q['id']}: missing placeholder_roles"
    else:
        assert q["placeholder_roles"] == [], f"{q['id']}: should have empty placeholder_roles"

pinyin_qs = [q for q in questions if q["category"] == "汉语拼音"]
vocab_qs  = [q for q in questions if q["category"] == "词汇"]
assert len(pinyin_qs) == 87, f"Expected 87 pinyin, got {len(pinyin_qs)}"
assert len(vocab_qs)  == 79, f"Expected 79 vocab, got {len(vocab_qs)}"

print(json.dumps(questions, ensure_ascii=False, indent=2))
